### ISSUE TITLE
New update broke it

### ISSUE THREAD

**Issue by Greybane** [nmbook/pidgin-libbnet#5]
Blizzard released a new update: 1.27.1.7085
Can't find much info, just "Bug fixes and general maintenance"

Getting the following error: Old version (W3XP_IX86_1xx_127b_enUS.mpq).

**Comment by nmbook** [comment]
This should depend on the BNLS server used.

**Comment by Greybane** [comment]
phix.no-ip.org is the only one that seems to work at the moment.
